jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      ghc-8.6.4:
        containerResource: quay.io/haskell_works/ghc-8.6.4:latest

      ghc-8.4.4:
        containerResource: quay.io/haskell_works/ghc-8.6.4:latest

  container: $[ variables['containerResource'] ]

  steps:
    - script: ghc --version && cabal --version
      displayName: Print GHC version

    - script: cabal v2-update
      displayName: Run cabal update

    - script: cabal v2-configure
      displayName: Configure the project

    # - script: cabal new-build --enable-tests --enable-benchmarks
    #   displayName: Build project


